# HumanEval Evaluation Configuration
# This file defines all experiment configurations for running inference and evaluation

# vLLM Server Settings
vllm:
  api_url: "http://localhost:8000/v1"
  max_tokens: 1024  # Increased from 512 to allow longer implementations
  top_p: 1.0
  stop_sequences:
    - "\n\n"
    - "\ndef "
    - "\nclass "

# Inference Settings
inference:
  num_workers: 16  # Parallel API calls (default: 16 for I/O-bound tasks)

# Evaluation Settings
evaluation:
  timeout: 3  # Timeout per test in seconds
  num_workers: null  # null = auto-detect CPU count
  results_dir: "results"

# Dataset Settings
dataset:
  max_samples: null  # null = run on all 164 problems

# Experiment Configurations
# Each experiment defines a unique combination of prompt strategy and settings
experiments:
  - name: "infilling_none"
    description: "Code infilling with TODO markers (no post-processing)"
    enabled: false
    prompt_strategy: "infilling"
    postprocess_strategy: "none"
    temperature: 0.2
    output_file: "completions_infilling_none.jsonl"
    results_file: "evaluation_infilling_none.json"

  - name: "minimal_none"
    description: "Minimal prompt (no post-processing)"
    enabled: false
    prompt_strategy: "minimal"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_minimal_none.jsonl"
    results_file: "evaluation_minimal_none.json"

  - name: "instructional_none"
    description: "Instructional prompt emphasizing correctness"
    enabled: false
    prompt_strategy: "instructional"
    postprocess_strategy: "none"
    temperature: 0.1
    output_file: "completions_instructional_none.jsonl"
    results_file: "evaluation_instructional_none.json"

  - name: "fewshot_none"
    description: "Few-shot prompt with 14 examples - DISABLED due to token length"
    enabled: false
    prompt_strategy: "fewshot"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_none.jsonl"
    results_file: "evaluation_fewshot_none.json"

  - name: "fewshot_v1_none"
    description: "Few-shot v1 (6 curated examples, no post-processing)"
    enabled: false
    prompt_strategy: "fewshot_v1"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_v1_none.jsonl"
    results_file: "evaluation_fewshot_v1_none.json"

  - name: "fewshot_v2_none"
    description: "Few-shot v2 (6 examples + chain of thought, no post-processing)"
    enabled: true
    prompt_strategy: "fewshot_v2"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_v2_none.jsonl"
    results_file: "evaluation_fewshot_v2_none.json"

  - name: "fewshot_v3_none"
    description: "Few-shot v3 (6 examples + CoT + self-critique, no post-processing)"
    enabled: false
    prompt_strategy: "fewshot_v3"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_v3_none.jsonl"
    results_file: "evaluation_fewshot_v3_none.json"

  - name: "cot_none"
    description: "Chain of thought reasoning prompt"
    enabled: false
    prompt_strategy: "cot"
    postprocess_strategy: "none"
    temperature: 0.3
    output_file: "completions_cot_none.jsonl"
    results_file: "evaluation_cot_none.json"

  - name: "datadriven_none"
    description: "Data-driven prompt based on analysis of all 164 problems"
    enabled: false
    prompt_strategy: "datadriven"
    postprocess_strategy: "none"
    temperature: 0.2
    output_file: "completions_datadriven_none.jsonl"
    results_file: "evaluation_datadriven_none.json"

  - name: "expert_none"
    description: "Expert-engineered prompt with self-review, persona, edge cases"
    enabled: false
    prompt_strategy: "expert"
    postprocess_strategy: "none"
    temperature: 0.2
    output_file: "completions_expert_none.jsonl"
    results_file: "evaluation_expert_none.json"

  - name: "helper_none"
    description: "Helper prompt with code patterns"
    enabled: false
    prompt_strategy: "helper"
    postprocess_strategy: "none"
    temperature: 0.2
    output_file: "completions_helper_none.jsonl"
    results_file: "evaluation_helper_none.json"

  - name: "optimized_v1_none"
    description: "Optimized prompt v1"
    enabled: false
    prompt_strategy: "optimized_v1"
    postprocess_strategy: "none"
    temperature: 0.2
    output_file: "completions_optimized_v1_none.jsonl"
    results_file: "evaluation_optimized_v1_none.json"

  - name: "optimized_v2_none"
    description: "Optimized prompt v2"
    enabled: false
    prompt_strategy: "optimized_v2"
    postprocess_strategy: "none"
    temperature: 0.2
    output_file: "completions_optimized_v2_none.jsonl"
    results_file: "evaluation_optimized_v2_none.json"

  - name: "optimized_v3_none"
    description: "Optimized prompt v3"
    enabled: false
    prompt_strategy: "optimized_v3"
    postprocess_strategy: "none"
    temperature: 0.2
    output_file: "completions_optimized_v3_none.jsonl"
    results_file: "evaluation_optimized_v3_none.json"

  - name: "opt1_none"
    description: "Category-based prompt with targeted guidance per problem type"
    enabled: false
    prompt_strategy: "opt1"
    postprocess_strategy: "none"
    temperature: 0.2
    output_file: "completions_opt1_none.jsonl"
    results_file: "evaluation_opt1_none.json"

  - name: "minimal_v0_none"
    description: "Expert-framed prompt focused on string manipulation only"
    enabled: false
    prompt_strategy: "minimal_v0"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_minimal_v0_none.jsonl"
    results_file: "evaluation_minimal_v0_none.json"

  - name: "expert_v00_none"
    description: "Smart prompt: direct 'expert in Python string manipulation' for string problems"
    enabled: false
    prompt_strategy: "expert_v00"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_expert_v00_none.jsonl"
    results_file: "evaluation_expert_v00_none.json"

  - name: "expert_v0_none"
    description: "Smart prompt: expert framing only for detected string problems, minimal otherwise"
    enabled: false
    prompt_strategy: "expert_v0"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_expert_v0_none.jsonl"
    results_file: "evaluation_expert_v0_none.json"

  - name: "expert_v1_none"
    description: "Smart prompt: string expert OR list expert OR minimal (two experts)"
    enabled: false
    prompt_strategy: "expert_v1"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_expert_v1_none.jsonl"
    results_file: "evaluation_expert_v1_none.json"

  - name: "expert_v2_none"
    description: "Smart prompt: string OR list OR sorting expert OR minimal (three experts)"
    enabled: false
    prompt_strategy: "expert_v2"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_expert_v2_none.jsonl"
    results_file: "evaluation_expert_v2_none.json"

  - name: "example_v0_none"
    description: "Smart prompt: minimal + one relevant example (string/list/sorting)"
    enabled: false
    prompt_strategy: "example_v0"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_example_v0_none.jsonl"
    results_file: "evaluation_example_v0_none.json"

  - name: "minimal_v2_none"
    description: "Minimal prompt with 'return' starter hint"
    enabled: false
    prompt_strategy: "minimal_v2"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_minimal_v2_none.jsonl"
    results_file: "evaluation_minimal_v2_none.json"

  - name: "minimal_v3_none"
    description: "Ultra-minimal prompt with just problem + newline"
    enabled: false
    prompt_strategy: "minimal_v3"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_minimal_v3_none.jsonl"
    results_file: "evaluation_minimal_v3_none.json"

  - name: "minimal_v4_none"
    description: "Minimal prompt with indentation hint"
    enabled: false
    prompt_strategy: "minimal_v4"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_minimal_v4_none.jsonl"
    results_file: "evaluation_minimal_v4_none.json"

  - name: "minimal_v5_none"
    description: "Bare minimal prompt - just rstrip() with no additions"
    enabled: false
    prompt_strategy: "minimal_v5"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_minimal_v5_none.jsonl"
    results_file: "evaluation_minimal_v5_none.json"

  - name: "minimal_v6_none"
    description: "Minimal prompt with anti-stub instruction"
    enabled: false
    prompt_strategy: "minimal_v6"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_minimal_v6_none.jsonl"
    results_file: "evaluation_minimal_v6_none.json"

  - name: "minimal_v7_none"
    description: "Balanced prompt focusing on critical failure points"
    enabled: false
    prompt_strategy: "minimal_v7"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_minimal_v7_none.jsonl"
    results_file: "evaluation_minimal_v7_none.json"

  - name: "minimal_post_v1"
    description: "Minimal prompt with post_v1 post-processing (fix crashes only)"
    enabled: false
    prompt_strategy: "minimal"
    postprocess_strategy: "post_v1"
    temperature: 0.0
    output_file: "completions_minimal_post_v1.jsonl"
    results_file: "evaluation_minimal_post_v1.json"

  - name: "minimal_post_v5"
    description: "Minimal prompt with post_v5 post-processing (production-ready pipeline)"
    enabled: false
    prompt_strategy: "minimal"
    postprocess_strategy: "post_v5"
    temperature: 0.0
    output_file: "completions_minimal_post_v5.jsonl"
    results_file: "evaluation_minimal_post_v5.json"

  - name: "fewshot_post_v5"
    description: "Few-shot prompt (14 examples) with post_v5 post-processing - DISABLED due to token length"
    enabled: false
    prompt_strategy: "fewshot"
    postprocess_strategy: "post_v5"
    temperature: 0.0
    output_file: "completions_fewshot_post_v5.jsonl"
    results_file: "evaluation_fewshot_post_v5.json"

  - name: "fewshot_v1_post_v5"
    description: "Few-shot v1 (6 curated examples) with post_v5 post-processing"
    enabled: false
    prompt_strategy: "fewshot_v1"
    postprocess_strategy: "post_v5"
    temperature: 0.0
    output_file: "completions_fewshot_v1_post_v5.jsonl"
    results_file: "evaluation_fewshot_v1_post_v5.json"

  - name: "fewshot_v2_post_v5"
    description: "Few-shot v2 (6 examples + CoT) with post_v5 post-processing"
    enabled: false
    prompt_strategy: "fewshot_v2"
    postprocess_strategy: "post_v5"
    temperature: 0.0
    output_file: "completions_fewshot_v2_post_v5.jsonl"
    results_file: "evaluation_fewshot_v2_post_v5.json"

  - name: "json_v1_none"
    description: "Few-shot with JSON-structured reasoning (no post-processing)"
    enabled: false
    prompt_strategy: "json_v1"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_json_v1_none.jsonl"
    results_file: "evaluation_json_v1_none.json"

  - name: "json_v1_post_v5"
    description: "Few-shot with JSON-structured reasoning + post_v5 post-processing"
    enabled: false
    prompt_strategy: "json_v1"
    postprocess_strategy: "post_v5"
    temperature: 0.0
    output_file: "completions_json_v1_post_v5.jsonl"
    results_file: "evaluation_json_v1_post_v5.json"

  - name: "fewshot_v3_post_v5"
    description: "Few-shot v3 (6 examples + CoT + self-critique) with post_v5 post-processing"
    enabled: false
    prompt_strategy: "fewshot_v3"
    postprocess_strategy: "post_v5"
    temperature: 0.0
    output_file: "completions_fewshot_v3_post_v5.jsonl"
    results_file: "evaluation_fewshot_v3_post_v5.json"

  - name: "fewshot_v4_none"
    description: "Few-shot v4 (9 examples + anti-placeholder warnings + edge cases, no post-processing) - Based on v2 failure analysis"
    enabled: false
    prompt_strategy: "fewshot_v4"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_v4_none.jsonl"
    results_file: "evaluation_fewshot_v4_none.json"

  - name: "fewshot_v4_post_v5"
    description: "Few-shot v4 (9 examples + anti-placeholder + edge cases) with post_v5 - RECOMMENDED for testing v2 improvements"
    enabled: false
    prompt_strategy: "fewshot_v4"
    postprocess_strategy: "post_v5"
    temperature: 0.0
    output_file: "completions_fewshot_v4_post_v5.jsonl"
    results_file: "evaluation_fewshot_v4_post_v5.json"

  - name: "fewshot_v5_none"
    description: "Few-shot v5 (9 targeted examples: prime, sort, search, comparison, data structures) - Addresses 100% failure classes"
    enabled: false
    prompt_strategy: "fewshot_v5"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_v5_none.jsonl"
    results_file: "evaluation_fewshot_v5_none.json"

  - name: "fewshot_v6_none"
    description: "Few-shot v6 - Pattern-based teaching (7 logic patterns) instead of examples"
    enabled: false
    prompt_strategy: "fewshot_v6"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_v6_none.jsonl"
    results_file: "evaluation_fewshot_v6_none.json"

  - name: "fewshot_v1_post_v7"
    description: "Few-shot v1 (6 examples) + post_v7 logic error fixes (hardcoded lists, delimiters, averages, rotations)"
    enabled: false
    prompt_strategy: "fewshot_v1"
    postprocess_strategy: "post_v7"
    temperature: 0.0
    output_file: "completions_fewshot_v1_post_v7.jsonl"
    results_file: "evaluation_fewshot_v1_post_v7.json"

  - name: "fewshot_v2_post_v7"
    description: "Few-shot v2 (6 examples + CoT) + post_v7 logic error fixes (hardcoded lists, delimiters, averages, rotations)"
    enabled: false
    prompt_strategy: "fewshot_v2"
    postprocess_strategy: "post_v7"
    temperature: 0.0
    output_file: "completions_fewshot_v2_post_v7.jsonl"
    results_file: "evaluation_fewshot_v2_post_v7.json"

  - name: "fewshot_v2_devise_none"
    description: "Few-shot v2_devise (6 examples + explicit 'devise algorithm' instruction, no post-processing)"
    enabled: true
    prompt_strategy: "fewshot_v2_devise"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_v2_devise_none.jsonl"
    results_file: "evaluation_fewshot_v2_devise_none.json"

  - name: "fewshot_v2_devise_post_v7"
    description: "Few-shot v2_devise (6 examples + 'devise algorithm') + post_v7 logic error fixes"
    enabled: true
    prompt_strategy: "fewshot_v2_devise"
    postprocess_strategy: "post_v7"
    temperature: 0.0
    output_file: "completions_fewshot_v2_devise_post_v7.jsonl"
    results_file: "evaluation_fewshot_v2_devise_post_v7.json"

  - name: "def_v1_none"
    description: "Definitions only (10 programming concepts + 'devise algorithm', no post-processing)"
    enabled: true
    prompt_strategy: "fewshot_v2_devise_def_v1"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_def_v1_none.jsonl"
    results_file: "evaluation_def_v1_none.json"

  - name: "def_v1_post_v7"
    description: "Definitions only (10 programming concepts + 'devise algorithm') + post_v7 logic error fixes"
    enabled: true
    prompt_strategy: "fewshot_v2_devise_def_v1"
    postprocess_strategy: "post_v7"
    temperature: 0.0
    output_file: "completions_def_v1_post_v7.jsonl"
    results_file: "evaluation_def_v1_post_v7.json"

  - name: "def_v2_none"
    description: "Optimized hybrid (5 definitions with code snippets + 4 examples + 'devise algorithm', no post-processing)"
    enabled: true
    prompt_strategy: "fewshot_v2_devise_def_v2"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_def_v2_none.jsonl"
    results_file: "evaluation_def_v2_none.json"

  - name: "def_v2_post_v7"
    description: "Optimized hybrid (5 definitions with code + 4 examples + 'devise algorithm') + post_v7 logic error fixes"
    enabled: true
    prompt_strategy: "fewshot_v2_devise_def_v2"
    postprocess_strategy: "post_v7"
    temperature: 0.0
    output_file: "completions_def_v2_post_v7.jsonl"
    results_file: "evaluation_def_v2_post_v7.json"
