vllm:
  # Model enablement - only one can be enabled at a time
  completion_model_enabled: false
  instruct_model_enabled: true

  completion_api_url: http://localhost:8000/v1
  completion_model: Qwen/Qwen2.5-Coder-0.5B
  chat_api_url: http://localhost:8001/v1
  chat_model: Qwen/Qwen2.5-Coder-0.5B-Instruct
  max_tokens: 1024
  top_p: 1.0

  # Stop sequences for completion mode (Base model)
  completion_stop_sequences:
  - '\n\n'
  - '\ndef '
  - '\nclass '

  # Stop sequences for chat mode (Instruct model)
  # Empty list to avoid interfering with markdown code blocks
  chat_stop_sequences: []
inference:
  num_workers: 16
evaluation:
  timeout: 3
  num_workers: null
  results_dir: results
dataset:
  max_samples: null
experiments:
- enabled: false
  prompt_strategy: minimal
  api_mode: completion
  postprocess_strategy: none
  temperature: 0.0
- enabled: false
  prompt_strategy: minimal
  api_mode: completion
  postprocess_strategy: post_v1
  temperature: 0.0
- enabled: false
  prompt_strategy: minimal
  api_mode: completion
  postprocess_strategy: post_v5
  temperature: 0.0
- enabled: false
  prompt_strategy: minimal
  api_mode: completion
  postprocess_strategy: post_v7
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v1
  api_mode: completion
  postprocess_strategy: none
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v1
  api_mode: completion
  postprocess_strategy: post_v5
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v1
  api_mode: completion
  postprocess_strategy: post_v7
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v2
  api_mode: completion
  postprocess_strategy: none
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v2
  api_mode: completion
  postprocess_strategy: post_v5
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v2
  api_mode: completion
  postprocess_strategy: post_v7
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v2_devise
  api_mode: completion
  postprocess_strategy: none
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v2_devise
  api_mode: completion
  postprocess_strategy: post_v7
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v1
  api_mode: completion
  postprocess_strategy: none
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v1
  api_mode: chat
  postprocess_strategy: auto  # Auto-load from strategy folder
  temperature: 0.0
- enabled: true
  prompt_strategy: fewshot_v1_cot
  api_mode: chat
  postprocess_strategy: auto  # Auto-load from strategy folder
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v1
  api_mode: chat
  postprocess_strategy: post_v5
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v1
  api_mode: chat
  postprocess_strategy: post_v7
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v2
  api_mode: chat
  postprocess_strategy: none
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v2
  api_mode: chat
  postprocess_strategy: post_v5
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v2
  api_mode: chat
  postprocess_strategy: post_v7
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v2_devise
  api_mode: chat
  postprocess_strategy: none
  temperature: 0.0
- enabled: false
  prompt_strategy: fewshot_v2_devise
  api_mode: chat
  postprocess_strategy: post_v7
  temperature: 0.0
