# HumanEval Evaluation Configuration
# This file defines all experiment configurations for running inference and evaluation

# vLLM Server Settings
vllm:
  api_url: "http://localhost:8000/v1"
  max_tokens: 1024  # Increased from 512 to allow longer implementations
  top_p: 1.0
  stop_sequences:
    - "\n\n"
    - "\ndef "
    - "\nclass "

# Inference Settings
inference:
  num_workers: 16  # Parallel API calls (default: 16 for I/O-bound tasks)

# Evaluation Settings
evaluation:
  timeout: 3  # Timeout per test in seconds
  num_workers: null  # null = auto-detect CPU count
  results_dir: "results"

# Dataset Settings
dataset:
  max_samples: null  # null = run on all 164 problems

# Experiment Configurations
# Each experiment defines a unique combination of prompt strategy and settings
# Available prompt strategies: minimal, fewshot_v1, fewshot_v2, fewshot_v2_devise
# Available post-processing: none, post_v1, post_v5, post_v7
experiments:
  # Minimal Prompt Experiments
  - name: "minimal_none"
    description: "Minimal prompt (no post-processing)"
    enabled: false
    prompt_strategy: "minimal"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_minimal_none.jsonl"
    results_file: "evaluation_minimal_none.json"

  - name: "minimal_post_v1"
    description: "Minimal prompt with post_v1 post-processing (fix crashes only)"
    enabled: false
    prompt_strategy: "minimal"
    postprocess_strategy: "post_v1"
    temperature: 0.0
    output_file: "completions_minimal_post_v1.jsonl"
    results_file: "evaluation_minimal_post_v1.json"

  - name: "minimal_post_v5"
    description: "Minimal prompt with post_v5 post-processing (production-ready pipeline)"
    enabled: false
    prompt_strategy: "minimal"
    postprocess_strategy: "post_v5"
    temperature: 0.0
    output_file: "completions_minimal_post_v5.jsonl"
    results_file: "evaluation_minimal_post_v5.json"

  - name: "minimal_post_v7"
    description: "Minimal prompt with post_v7 post-processing (logic error fixes)"
    enabled: false
    prompt_strategy: "minimal"
    postprocess_strategy: "post_v7"
    temperature: 0.0
    output_file: "completions_minimal_post_v7.jsonl"
    results_file: "evaluation_minimal_post_v7.json"

  # Few-shot v1 Experiments (6 curated examples)
  - name: "fewshot_v1_none"
    description: "Few-shot v1 (6 curated examples, no post-processing)"
    enabled: false
    prompt_strategy: "fewshot_v1"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_v1_none.jsonl"
    results_file: "evaluation_fewshot_v1_none.json"

  - name: "fewshot_v1_post_v5"
    description: "Few-shot v1 (6 curated examples) with post_v5 post-processing"
    enabled: false
    prompt_strategy: "fewshot_v1"
    postprocess_strategy: "post_v5"
    temperature: 0.0
    output_file: "completions_fewshot_v1_post_v5.jsonl"
    results_file: "evaluation_fewshot_v1_post_v5.json"

  - name: "fewshot_v1_post_v7"
    description: "Few-shot v1 (6 examples) + post_v7 logic error fixes"
    enabled: false
    prompt_strategy: "fewshot_v1"
    postprocess_strategy: "post_v7"
    temperature: 0.0
    output_file: "completions_fewshot_v1_post_v7.jsonl"
    results_file: "evaluation_fewshot_v1_post_v7.json"

  # Few-shot v2 Experiments (6 examples + chain of thought)
  - name: "fewshot_v2_none"
    description: "Few-shot v2 (6 examples + chain of thought, no post-processing)"
    enabled: true
    prompt_strategy: "fewshot_v2"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_v2_none.jsonl"
    results_file: "evaluation_fewshot_v2_none.json"

  - name: "fewshot_v2_post_v5"
    description: "Few-shot v2 (6 examples + CoT) with post_v5 post-processing"
    enabled: false
    prompt_strategy: "fewshot_v2"
    postprocess_strategy: "post_v5"
    temperature: 0.0
    output_file: "completions_fewshot_v2_post_v5.jsonl"
    results_file: "evaluation_fewshot_v2_post_v5.json"

  - name: "fewshot_v2_post_v7"
    description: "Few-shot v2 (6 examples + CoT) + post_v7 logic error fixes"
    enabled: false
    prompt_strategy: "fewshot_v2"
    postprocess_strategy: "post_v7"
    temperature: 0.0
    output_file: "completions_fewshot_v2_post_v7.jsonl"
    results_file: "evaluation_fewshot_v2_post_v7.json"

  # Few-shot v2_devise Experiments (6 examples + "devise algorithm" instruction) [BEST]
  - name: "fewshot_v2_devise_none"
    description: "Few-shot v2_devise (6 examples + explicit 'devise algorithm' instruction, no post-processing)"
    enabled: true
    prompt_strategy: "fewshot_v2_devise"
    postprocess_strategy: "none"
    temperature: 0.0
    output_file: "completions_fewshot_v2_devise_none.jsonl"
    results_file: "evaluation_fewshot_v2_devise_none.json"

  - name: "fewshot_v2_devise_post_v7"
    description: "Few-shot v2_devise (6 examples + 'devise algorithm') + post_v7 logic error fixes [BEST: 57/164 = 34.8%]"
    enabled: true
    prompt_strategy: "fewshot_v2_devise"
    postprocess_strategy: "post_v7"
    temperature: 0.0
    output_file: "completions_fewshot_v2_devise_post_v7.jsonl"
    results_file: "evaluation_fewshot_v2_devise_post_v7.json"
