services:
  vllm-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.vllm
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=Qwen/Qwen2.5-Coder-0.5B
      - PORT=8000
      - HOST=0.0.0.0
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    # GPU support - comment out for CPU-only mode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    shm_size: '2gb'  # Required for vLLM

  # Evaluation sandbox container
  eval-sandbox:
    build:
      context: .
      dockerfile: docker/Dockerfile.eval
    depends_on:
      vllm-server:
        condition: service_healthy
    volumes:
      - ./scripts:/app/scripts
      - ./prompts:/app/prompts
      - ./results:/app/results
    environment:
      - VLLM_API_URL=http://vllm-server:8000/v1
    network_mode: "service:vllm-server"

volumes:
  huggingface_cache:
