[project]
name = "microsoft-take-home"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "autopep8>=2.3.2",
    "datasets>=4.1.1",
    "docker>=7.1.0",
    "openai>=2.2.0",
    "ruff>=0.14.0",
    "vllm>=0.11.0",
]
